---
title: "Figura1_technosperm"
author: "Francisco Madrid"
date: '2022-11-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MUVR)
```


```{r}
permTotal_IVF <- readRDS("C:/Users/Biosignal/Documents/IMIM/Tecniosperm2/permTotal_IVF.RDS")
model_IVF <- readRDS("C:/Users/Biosignal/Documents/IMIM/Tecniosperm2/model_IVF.RDS")

model_funcion <- readRDS("C:/Users/Biosignal/Documents/IMIM/Tecniosperm2/model_funcion.RDS")
permTotal_model_funcion <- readRDS("C:/Users/Biosignal/Documents/IMIM/Tecniosperm2/permTotal_model_funcion.RDS")

permTotal_model_calidad1 <- readRDS("C:/Users/Biosignal/Documents/IMIM/Tecniosperm2/permTotal_model_calidad1.RDS")
model_calidad1 <- readRDS("C:/Users/Biosignal/Documents/IMIM/Tecniosperm2/model_calidad1.RDS")

```


# All figures below

```{r}
#| fig-asp: 1.5
#| fig-height: 10
#| fig-width: 6
par(mfrow=c(3, 2))

plotMV(model_calidad1)
mtext("A", side = 3, adj = 0, line = 1)

MUVR::plotPerm(model_calidad1[["fitMetric"]][["Q2"]][2], permTotal_model_calidad1, type ="t",xlab = "Q2", side = "greater", breaks = 50, pos = 3)


plotMV(model_funcion)
mtext("B", side = 3, adj=0, line = 1)

MUVR::plotPerm(model_funcion[["fitMetric"]][["Q2"]][2], permTotal_model_funcion, type ="t",xlab = "Q2",
               side = "greater", breaks = 50, pos = 3)


plotMV(model_IVF)
mtext("C", side = 3, adj = 0, line = 1)

MUVR::plotPerm(model_IVF[["fitMetric"]][["Q2"]][2], permTotal_IVF[1:500], type ="t", xlab = "Q2",
               side = "greater", breaks = 50, pos = 3)

```

